# Compiling options:
language: cpp
compiler:
  - gcc
script: cmake . && make
before_install:
  - sudo apt-get install libboost-dev libsdl1.2-dev

# Travis options

# Blacklist
branches:
  except:
    - /tmp.*/
