# Compiling options:
language: cpp
compiler:
  - gcc
script: cmake . && make
before_install:
  - sudo apt-get -qq install libboost1.48-all-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-ttf1.2-dev

# Travis options

# Blacklist
branches:
  except:
    - /tmp.*/
